# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum

class FuzbAISimulator:
    r"""
    High level simulation wrapping the MuJoCo physical
    simulation of the table football.
    # SAFETY
    This is NOT THREAD-SAFE. This is due to [`MjData`] not being thread-safe even though
    it passes the checks. Several bypasses were made for performance reasons as it is not meant
    to be shared between threads. However, multiple [`FuzbAISimulator`] instances can be made
    safely in individual threads or within the same thread.
    """
    terminated: builtins.bool
    truncated: builtins.bool
    score: builtins.list[builtins.int]
    r"""
    Returns the current score. The score is formatted as: [RED - BLUE].
    """
    collision_forces: builtins.list[builtins.list[builtins.float]]
    r"""
    Returns the collision forces (relative to the red team).
    """
    collision_indices: builtins.list[builtins.int]
    r"""
    Returns the collision indices (relative to the red team).
    """
    simulated_delay_s: builtins.float
    r"""
    Returns the configured simulated delay (in seconds).
    """
    viewer_running: builtins.bool
    r"""
    Checks if the viewier is still running. If the viewer is not running or has never been
    created, [`false`] is returned.
    """
    def __new__(cls, internal_step_factor:builtins.int, sample_steps:builtins.int, realtime:builtins.bool, simulated_delay_s:builtins.float, model_path:typing.Optional[builtins.str], visual_config:SimVisualConfig) -> FuzbAISimulator:
        r"""
        Constructs a new [`FuzbAISimulator`] instance.
        """
    def ball_true_state(self) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float, builtins.float, builtins.float]:
        r"""
        Returns the ball's TRUE state (without noise) in the format
        (x, y, z, vx, vy)
        """
    def rods_true_state(self) -> tuple[builtins.list[builtins.float], builtins.list[builtins.float]]: ...
    def observation(self, team:PlayerTeam) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float, builtins.list[builtins.float], builtins.list[builtins.float]]:
        r"""
        Returns the observation of the simulation.
        The observation represents real-world like state with added
        noise. It includes the ball's state and the state of each rod.
        The parameter `team` controls which team's coordinate system the data should be relative to.
        The returned data is in format (ball_state, rod_positions, rod_rotations)
        """
    def delayed_observation(self, team:PlayerTeam, delay:typing.Optional[builtins.float]) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float, builtins.list[builtins.float], builtins.list[builtins.float]]:
        r"""
        Same as [`observation`](FuzbAISimulator::observation) but delayed.
        The delay can be optionally specified by `delay`, otherwise the internally set one is used.
        """
    def set_simulated_delay(self, simulated_delay_s:builtins.float) -> None:
        r"""
        Sets the simulated delay (in seconds) to `simulated_delay_s`.
        """
    def set_ball_damping(self, damping:typing.Sequence[builtins.float]) -> None: ...
    def set_rod_states(self, positions:typing.Optional[typing.Sequence[builtins.float]], rotations:typing.Optional[typing.Sequence[builtins.float]]) -> None:
        r"""
        Sets the joint state of individual rod to `positions` and `rotations`.
        The position is in range of: [0, 1], while the rotation in range [-1, 1].
        The ranges thus match actions of [`set_motor_command`](FuzbAISimulator::set_motor_command)
        Everything is done relative to the red's coordinate system.
        """
    def set_built_in_disabled_rods(self, team:PlayerTeam, indices:typing.Sequence[builtins.int]) -> None:
        r"""
        Proxy method to the built-in player's `set_disabled` method.
        """
    def set_external_mode(self, team:PlayerTeam, enable:builtins.bool) -> None:
        r"""
        Configures whether the specific `team` should obtain commands externally (`enable` = `true`)
        or internally (`enable` = `false`, the agent is stored within the simulation).
        """
    def set_motor_command(self, commands:typing.Sequence[tuple[builtins.int, builtins.float, builtins.float, builtins.float, builtins.float]], team:PlayerTeam) -> None:
        r"""
        Sets new motor (rod movement) commands for the specified `team`.
        The commands will be applied at the next call to [`step_simulation`](FuzbAISimulator::step_simulation)
        """
    def fill_delay_buffer(self) -> None:
        r"""
        Fills the delay buffer, allowing information to be fully delayed from the beginning of reset.
        """
    def serve_ball(self, position:typing.Optional[typing.Sequence[builtins.float]]) -> None:
        r"""
        Servers the ball to a given `position`.
        """
    def nudge_ball(self, velocity:typing.Optional[typing.Sequence[builtins.float]]) -> None: ...
    def clear_score(self) -> None:
        r"""
        Clears the score to [0-0];
        """
    def clear_trace(self) -> None: ...
    def show_estimates(self, ball_xyz:typing.Optional[typing.Sequence[builtins.float]], rod_tr:typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]]) -> None:
        r"""
        Draws the ball's and the rods' estimated states to the viewer.
        The ``rod_tr`` parameter is an array of ``[translation, rotation]``,
        where the translation is in normalized units [0..1] and the rotation is in range of
        [-64, 64], representing an entire circle (360 deg) in any direction.
        """
    def screenshot(self, ball_xyz:typing.Optional[typing.Sequence[builtins.float]], rod_tr:typing.Optional[typing.Sequence[typing.Sequence[builtins.float]]], camera_id:typing.Optional[builtins.int], camera_name:typing.Optional[builtins.str], outfilename:typing.Optional[builtins.str], show_estimates:builtins.bool, show_trace:builtins.bool) -> typing.Optional[builtins.list[builtins.int]]:
        r"""
        Takes a screenshot of the current simulation state.
        Parameters `ball_xyz` and `rod_tr` are optional and if not given, the delayed noisy estimates
        will be displayed upon passing `show_estimates` as `true`. Passing `show_trace` as `true` will
        draw past ball positions in the form of a line trace. Screenshots can be taken from any camera,
        which can be selected either directly by id (`camera_id`) or indirectly via name (`camera_name`).
        Finally, the image can be written to a file (`outfilename`) or else given as a return value.
        """
    def reset_simulation(self) -> None: ...
    def step_simulation(self) -> None: ...
    @staticmethod
    def local_to_global(position:typing.Optional[typing.Sequence[builtins.float]], velocity:typing.Optional[typing.Sequence[builtins.float]]) -> tuple[typing.Optional[builtins.list[builtins.float]], typing.Optional[builtins.list[builtins.float]]]:
        r"""
        Transforms local coordinates (from the read team) into Mujoco's global coordinate system.
        Method assumes that `position` is in mm, whilst the output is in m (as expected by MuJoCo).
        The `velocity` is in m/s and so is the output.
        """
    @staticmethod
    def transform_observation_red_to_blue(observation:tuple[builtins.float, builtins.float, builtins.float, builtins.float, typing.Sequence[builtins.float], typing.Sequence[builtins.float]]) -> tuple[builtins.float, builtins.float, builtins.float, builtins.float, builtins.list[builtins.float], builtins.list[builtins.float]]:
        r"""
        Transforms the observation from the red's coordinate system into the blue's.
        """
    def _set_actuator_parameters(self, actuator_id:builtins.int, kp:builtins.float, kd:builtins.float, max_vel:builtins.float, max_acc:builtins.float) -> None:
        r"""
        Sets the actuator control parameters.
        ``actuator_id`` of [0-7] represents translational actuators, ``actuator_id`` of [8-15]
        represents rotational actuators.
        """

class SimVisualConfig:
    r"""
    Specifies visualization related parameters of 
    the [`FuzbAISimulator`] struct.
    # Arguments
    * `trace_length` - How many previous ball positions should be visible.
    * `refresh_steps` - How many low-level steps before re-rendering the viewer.
    * `screenshot_size` - Tuple of (width, height) for the offscreen renderer (for screenshots).
                          Set to None if no `.screenshot` calls are required.
    """
    def __new__(cls, trace_length:builtins.int, refresh_steps:builtins.int, screenshot_size:typing.Optional[tuple[builtins.int, builtins.int]]) -> SimVisualConfig: ...

class PlayerTeam(Enum):
    r"""
    Enumerates the two possible teams by color.
    """
    RED = ...
    BLUE = ...

